### ISSUE TITLE
Is this repo open for contributions or only for self practice?

### ISSUE THREAD

**Issue by JDeepD** [subnut/project-euler#1]

**Comment by subnut** [comment]
Sorry, forgot to add in the description that this repo contains _MY_ solutions to projecteuler.net
If you want to contribute, see TheAlgorithms/Python#2695 and [https://github.com/TheAlgorithms/Python/tree/master/project_euler](https://github.com/TheAlgorithms/Python/tree/master/project_euler)

BTW notice that this repo doesn't have a license.
FYI, you should never try to contribute to a repo without a proper **Open-source** License.
